"""Assemble the final Markdown report from metrics + the Claude narrative."""

from __future__ import annotations

from datetime import datetime, timezone


def render(
    payload: dict,
    narrative: str | None,
    *,
    repo_path: str,
    model: str | None,
) -> str:
    subject = payload["subject"]
    totals = payload["repository_totals"]
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []
    lines.append("# Contribution analysis")
    lines.append("")
    lines.append(f"_Generated {generated}._")
    lines.append("")
    lines.append(
        "> This report is built from **anonymized, aggregate git metadata only**. "
        "It contains no source code, no commit-message text, no file paths, and "
        "no real contributor identities. Other contributors appear as "
        "`Contributor A`, `Contributor B`, … Quantitative signals like commit "
        "counts and churn are proxies for activity, **not** measures of impact or "
        "code quality."
    )
    lines.append("")

    # --- AI narrative ----------------------------------------------------
    if narrative:
        lines.append(narrative.strip())
        lines.append("")
        if model:
            lines.append(f"_Narrative generated by `{model}`._")
            lines.append("")

    # --- Raw metrics -----------------------------------------------------
    lines.append("---")
    lines.append("")
    lines.append("## Your metrics (raw)")
    lines.append("")
    lines.append(
        f"- Repository contributors analyzed: **{totals['total_contributors']}** "
        f"({totals['total_commits']} commits total)"
    )
    lines.append(
        f"- Your rank by commit count: **#{subject['rank_by_commits']}** "
        f"of {totals['total_contributors']}"
    )
    lines.append(
        f"- Your share of all commits: **{_pct(subject['commit_share_of_repo'])}**"
    )
    lines.append("")
    lines.append(_metric_table(subject))
    lines.append("")

    # --- Peer comparison table ------------------------------------------
    lines.append("## Anonymized peer comparison")
    lines.append("")
    lines.append(_comparison_table(payload))
    lines.append("")
    if totals["peers_omitted"]:
        lines.append(
            f"_{totals['peers_omitted']} additional contributor(s) omitted from "
            "the table for brevity (included in totals)._"
        )
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"_Source repository: `{repo_path}` (local history)._")
    lines.append("")

    return "\n".join(lines)


def render_team(
    payload: dict,
    narrative: str | None,
    *,
    repo_path: str,
    model: str | None,
) -> str:
    """Render the whole-team, ranked analysis."""
    totals = payload["repository_totals"]
    identified = payload.get("identified", False)
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []
    lines.append("# Codebase contribution analysis")
    lines.append("")
    lines.append(f"_Generated {generated}._")
    lines.append("")
    identity_note = (
        "Contributors are shown by name (you opted in with `--identify`)."
        if identified
        else "Contributors are anonymized (`Contributor #1`, `#2`, …)."
    )
    lines.append(
        "> Built from **aggregate git metadata only** — no source code, no "
        "commit-message text, and no file paths are included or sent anywhere "
        f"(only bucketed counts). {identity_note} Ranking is by **commit "
        "volume, an activity proxy** — commit/line/ticket counts are gameable "
        "and are **not** measures of impact, seniority, or code quality. Read "
        "this as a conversation starter, not a verdict or a stack-rank."
    )
    lines.append("")
    lines.append(
        f"**{totals['contributors_ranked']}** of "
        f"**{totals['total_contributors']}** contributors ranked · "
        f"{totals['total_commits']} commits total."
    )
    lines.append("")

    if narrative:
        lines.append(narrative.strip())
        lines.append("")
        if model:
            lines.append(f"_Narrative generated by `{model}`._")
            lines.append("")
    else:
        # No-AI fallback: a structured per-contributor breakdown so the report
        # is useful without an API key.
        for c in payload["contributors"]:
            lines.append(_team_member_block(c))
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Ranked metrics (raw)")
    lines.append("")
    lines.append(_team_table(payload))
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"_Source repository: `{repo_path}` (local history)._")
    lines.append("")
    return "\n".join(lines)


def _team_table(payload: dict) -> str:
    header = (
        "| # | Contributor | Commits | Active mo. | Net churn | Tickets | "
        "Avg size | Top focus |"
    )
    sep = "| ---: | --- | ---: | ---: | ---: | ---: | ---: | --- |"
    rows = [header, sep]
    for c in payload["contributors"]:
        rows.append(
            f"| {c['rank']} | {c['label']} | {c['commits']} | "
            f"{c['active_months']} | {c['net_churn']} | "
            f"{c['distinct_tickets_referenced']} | "
            f"{c['avg_commit_size_lines']} | {_top_focus(c)} |"
        )
    return "\n".join(rows)


def _team_member_block(c: dict) -> str:
    out = [
        f"## #{c['rank']} — {c['label']}",
        (
            f"{c['commits']} commits | {c['active_months']} active months | "
            f"{c['distinct_tickets_referenced']} ticket refs | "
            f"{c['net_churn']} net churn lines"
        ),
        "",
        f"- Commit-type mix: {_fmt_counts(c['commit_categories'])}",
        f"- Topic focus: {_fmt_counts(c['topic_commits'])}",
        f"- Where they work: {_fmt_counts(c['path_categories'])}",
        f"- Cadence: {c['commits_per_active_month']} commits/active-month, "
        f"avg commit {c['avg_commit_size_lines']} lines",
        f"- Commit-time rhythm (UTC): {_fmt_hours(c['hour_distribution'])}",
    ]
    return "\n".join(out)


def _top_focus(c: dict) -> str:
    topics = c.get("topic_commits") or {}
    if topics:
        name, n = next(iter(topics.items()))
        return f"{name} ({n})"
    cats = c.get("commit_categories") or {}
    if cats:
        name, n = next(iter(cats.items()))
        return f"{name} ({n})"
    return "—"


def _fmt_counts(counts: dict, limit: int = 5) -> str:
    if not counts:
        return "—"
    items = list(counts.items())[:limit]
    return ", ".join(f"{k} ({v})" for k, v in items)


def _metric_table(m: dict) -> str:
    rows = [
        ("Commits", m["commits"]),
        ("Merge commits", m["merge_commits"]),
        ("Lines added", m["insertions"]),
        ("Lines removed", m["deletions"]),
        ("Net churn", m["net_churn"]),
        ("Avg commit size (lines)", m["avg_commit_size_lines"]),
        ("Distinct files touched", m["distinct_files_touched"]),
        ("Active days", m["active_days"]),
        ("Activity span (days)", m["span_days"]),
        ("Avg subject length (chars)", m["avg_subject_length_chars"]),
        ("Short-subject ratio", _pct(m["short_subject_ratio"])),
        ("First commit", m.get("first_commit") or "—"),
        ("Last commit", m.get("last_commit") or "—"),
    ]
    out = ["| Metric | Value |", "| --- | --- |"]
    out += [f"| {label} | {value} |" for label, value in rows]
    out.append("")
    out.append(f"- Top file types: {_fmt_extensions(m['top_extensions'])}")
    out.append(f"- Commit-time rhythm (UTC): {_fmt_hours(m['hour_distribution'])}")
    return "\n".join(out)


def _comparison_table(payload: dict) -> str:
    subject = payload["subject"]
    peers = payload["peers"]
    header = (
        "| Contributor | Commits | Net churn | Avg commit size | "
        "Files | Active days |"
    )
    sep = "| --- | ---: | ---: | ---: | ---: | ---: |"
    rows = [header, sep]
    rows.append(_comparison_row("**You**", subject))
    for peer in peers:
        rows.append(_comparison_row(peer["label"], peer))
    return "\n".join(rows)


def _comparison_row(label: str, m: dict) -> str:
    return (
        f"| {label} | {m['commits']} | {m['net_churn']} | "
        f"{m['avg_commit_size_lines']} | {m['distinct_files_touched']} | "
        f"{m['active_days']} |"
    )


def _fmt_extensions(ext: dict) -> str:
    if not ext:
        return "—"
    return ", ".join(f"`{k}` ({v})" for k, v in ext.items())


def _fmt_hours(hours: dict) -> str:
    return ", ".join(f"{k}: {_pct(v)}" for k, v in hours.items())


def _pct(value: float) -> str:
    return f"{round(value * 100)}%"
